### ISSUE TITLE
EnderSlayerEnchantment throwing exception

### ISSUE THREAD

**Issue by bootzin** [jacopouggeri/end_aspected#3]
In EnderSlayerEnchantment, in the method "getLastDamageInflicted", you should probably check if event.getSource().getEntity() is an instance of LivingEntity before casting. I got an exception where it tried to cast an EntityArrow to LivingEntity and crashed the game

**Comment by jacopouggeri** [comment]
Thanks for reporting this, I will fix it as soon as I can :)

**Comment by jacopouggeri** [comment]
As a curiosity, do you know how that happened? How did an arrow end up being the user of the enchantment?

**Comment by bootzin** [comment]
Sadly, I don't know, but I think it was an effect on a mob
